export const types = {
    AUTH_LOGIN_PROCESS: 'AUTH_LOGIN_PROCESS',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    LIST_LOADING_PROCESS: 'LIST_LOADING_PROCESS',
    LIST_LOADING_SUCCESS: 'LIST_LOADING_SUCCESS',
};